version: "3"
services:
  build:
    image: pihole-lists
    build:
      context: .
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        python -m main
    environment:
      - LISTS=$LISTS
    volumes:
      - ./src:/src:rw
  cleanup:
    image: pihole-lists
    build:
      context: .
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        python -m cleanup
    environment:
      - LISTS=$LISTS
    volumes:
      - ./src:/src:rw
